import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/bars/Navbar'
import LeftSidebar from '@/components/bars/LeftSidebar'
import Bottombar from '@/components/bars/Bottonbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar />
          <main className='flex flex-row'>
            <LeftSidebar />
            <section className='w-full'>
              <div >
                {children}
              </div>
            </section>
          </main>
          <Bottombar />
      </body>
    </html>
  )
}
